import {
  GlobalOutline,
  UserOutline,
  PlusOutline,
  FileSearchOutline,
  CheckOutline,
  CloseOutline,
  MinusOutline,
  PlusSquareOutline,
  HourglassOutline,
  SyncOutline,
  SettingOutline,
  UpOutline,
  ClockCircleFill,
  UnorderedListOutline,
  BellOutline,
} from '@ant-design/icons-angular/icons';

export const icons = [
  GlobalOutline,
  UserOutline,
  PlusOutline,
  MinusOutline,
  FileSearchOutline,
  CheckOutline,
  CloseOutline,
  PlusSquareOutline,
  HourglassOutline,
  SyncOutline,
  SettingOutline,
  UpOutline,
  ClockCircleFill,
  UnorderedListOutline,
  BellOutline,
];
